### PR TITLE
Phone num validation

### PR DESCRIPTION
**Pull request by BoxHezi**
Phone number validation will allow Australian mobile number only
phone type selection has been removed. Allow only mobile nubmer

### CODE REVIEW

**Comment by rockmanvnx6** [comment]
Changing variable name might cause response conflict. I'll test this.

**Comment by rockmanvnx6** [comment]
`ERROR in ./app/components/children/ManagerEmployeeAll.js
Module not found: Error: Cannot resolve module 'phone' in /Users/austin/Desktop/PROJECT FOLDER/Mystr/app/components/children
 @ ./app/components/children/ManagerEmployeeAll.js 3:12-28`

happens when run `npm dev run`

**Comment by MichaelDao** [comment]
Just fixed the weird conflict, i suggest we push the change, raise the bug as an issue

as long as we can get functionality out, we shouldnt worry about how robust the code is until the MCG manager approves our MVP. When our MVP is good to go, then we will look into styling, better code design and bug crushing.

**Comment by MichaelDao** [comment]
This doesnt exactly work yet @BoxHezi 

I might enter in a number such as 123, and it still allows it. I notice in the console log that a proper phone number gets logged, but it should be blocking any number that is not a full australian phone number.

**Comment by rockmanvnx6** [comment]
when putting the number as 041.... in the database it stores the 0, but when comes to manager update view. it deletes the first 0.

**Pull request merged**
